apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend-service
spec:
  type: NodePort
  selector:
    app: quiz-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: 31000
